let __BC_CLASSVIEW_NODE_ISTAG = "t";
let __BC_CLASSVIEW_NODE_TAGNAME = "n";
let __BC_CLASSVIEW_NODE_EXPOSEKEY = "e";
let __BC_CLASSVIEW_NODE_DOMEVENTHANDLERS = "d";
let __BC_CLASSVIEW_NODE_ATTRS = "a";
let __BC_CLASSVIEW_NODE_CHILDNODES = "c";

let __BC_CLASSVIEW_NODE_ISEXTENSIONPOINT = "E";

let __BC_CLASSVIEW_NODE_ISTEXT = "T";
let __BC_CLASSVIEW_NODE_VALUE = "v";

let __BC_CLASSVIEW_NODE_ISSUB = "s";
let __BC_CLASSVIEW_NODE_SUBPROP = "S";
