let __BC_TYPE_TYPE = "t";

let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_NUMBER = 1;
let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_STRING = 2;
let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_BOOLEAN = 3;

let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_LIST = 4;
let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_MAP = 5;
let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_SET = 6;

let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_DATETIME = 7;

let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_OBJECT = 8;

let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_ANY = 9;

let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_VOID = 10;

let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_SELF = 11;
let __BC_TYPE_TYPE_ENUMVAL_BUILTIN_CLASS = 12;

let __BC_TYPE_TYPE_ENUMVAL_USERDEFINED = 50;

let __BC_TYPE_NULLABLE = "n";

let __BC_TYPE_ARGUMENTS = "a";
