let __IP_OOML_PROPERTIES_STATE_CURRENTVALUE = "__OomlPropertiesStateCurrentValue";
let __IP_OOML_PROPERTIES_STATE_NODES = "__OomlPropertiesStateNodes";
let __IP_OOML_PROPERTIES_STATE_CUSTOM_HTML_ROOT_DOM_ELEMENTS = "__OomlPropertiesStateCustomHTMLRootDOMElements";
