let __IP_OOML_EVENTSOURCE_PROTO_RECEIVE_DISPATCH = "__OomlEventSourceProtoReceiveDispatch";
let __IP_OOML_EVENTSOURCE_PROTO_FORWARD_DISPATCH = "__OomlEventSourceProtoForwardDispatch";

let __IP_OOML_EVENTSOURCE_PROTO_FORWARD_CHANGE = "__OomlEventSourceProtoForwardChange";

let __IP_OOML_EVENTSOURCE_PROTO_CREATE_RENDERING = "__OomlEventSourceProtoCreateRendering";
let __IP_OOML_EVENTSOURCE_PROTO_DESTROY_RENDERING = "__OomlEventSourceProtoDestroyRendering";
