let __IP_OOML_RUNTIME_DOM_UPDATE_TREE_ACTION = "__OomlRuntimeDOMUpdateTreeAction";
let __IP_OOML_RUNTIME_DOM_UPDATE_TREE_ACTION_ENUMVAL_APPENDTO = 1;
let __IP_OOML_RUNTIME_DOM_UPDATE_TREE_ACTION_ENUMVAL_INSERTAFTER = 2;
let __IP_OOML_RUNTIME_DOM_UPDATE_TREE_ACTION_ENUMVAL_POTENTIALLYREMOVE = 3;

let __IP_OOML_RUNTIME_DOM_UPDATE_TREE_ACTION_ENUMVAL_ARRREINSERT = 4;
// Even though could just replace with POTENTIALLYREMOVE,
// use this to allow quickly disabling an ARRREINSERT
let __IP_OOML_RUNTIME_DOM_UPDATE_TREE_ACTION_ENUMVAL_ARRUNLOAD = 5;

let __IP_OOML_RUNTIME_DOM_UPDATE_TREE_ACTION_ARGUMENT = "__OomlRuntimeDOMUpdateTreeActionArgument";

let __IP_OOML_RUNTIME_DOM_UPDATE_CDATA_ACTION = "__OomlRuntimeDOMUpdateCDataAction";
let __IP_OOML_RUNTIME_DOM_UPDATE_CDATA_ACTION_ENUMVAL_UPDATETEXT = 6;
let __IP_OOML_RUNTIME_DOM_UPDATE_CDATA_ACTION_ENUMVAL_APPLYATTR = 7;

let __IP_OOML_RUNTIME_DOM_UPDATE_CDATA_ACTION_ARGUMENT = "__OomlRuntimeDOMUpdateCDataActionArgument";
